bin/test: $(call getfiles,test)
	@mkdir -p $(@D);
	@$(CC) -o $@ $^ $(shell ((test -f bin/libserum.so && realpath bin/libserum.so) || echo '-lserum'));


pre-test:
	@echo -n 'Building test: ';

test: pre-test bin/test
	@echo ' done.';
